language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.18"
  
script: "perl test_suite.pm"

install:
  - "cpanm --quiet --notest Test::More" 
  - "cpanm --quiet --notest Switch" 
  - "cpanm --quiet --notest experimental" 
  - "cpanm --quiet --notest Time::HiRes"

notifications:
  email:
    - christian.kuehnel@gmail.com
 