language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.18"
  
install:
    - cpanm -v --installdeps --notest .

script: "perl test_suite.pm"

notifications:
  recipients:
    - christian.kuehnel@gmail.com
  email:
    on_success: change
    on_failure: always
#env:
