language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.18"
  
script: "perl test_suite.pm"

install:
	- "cpanm Test::More" 
	- "cpanm Switch" 
	- "cpanm experimental" 
	- "cpanm Time::HiRes"

notifications:
  recipients:
    - christian.kuehnel@gmail.com
  email:
    on_success: change
    on_failure: always
