language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.18"
  
script: "perl test_suite.pm"

install:
  - "cpanm --quiet --installdeps --notest Test::More" 
  - "cpanm --quiet --installdeps --notest Switch" 
  - "cpanm --quiet --installdeps --notest experimental" 
  - "cpanm --quiet --installdeps --notest Time::HiRes"
